<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\State;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
//        $state = State::inRandomOrder()->limit(1)->first();
//        City::create(['state_id' => $state->id, 'name' => 'New York City', 'status' => 1]);

        DB::table('cities')->insertOrIgnore([
            ['name' => 'North and Middle Andaman', 'state_id' => 32],
            ['name' => 'South Andaman', 'state_id' => 32],
            ['name' => 'Nicobar', 'state_id' => 32],
            ['name' => 'Adilabad', 'state_id' => 1],
            ['name' => 'Anantapur', 'state_id' => 1],
            ['name' => 'Chittoor', 'state_id' => 1],
            ['name' => 'East Godavari', 'state_id' => 1],
            ['name' => 'Guntur', 'state_id' => 1],
            ['name' => 'Hyderabad', 'state_id' => 1],
            ['name' => 'Kadapa', 'state_id' => 1],
            ['name' => 'Karimnagar', 'state_id' => 1],
            ['name' => 'Khammam', 'state_id' => 1],
            ['name' => 'Krishna', 'state_id' => 1],
            ['name' => 'Kurnool', 'state_id' => 1],
            ['name' => 'Mahbubnagar', 'state_id' => 1],
            ['name' => 'Medak', 'state_id' => 1],
            ['name' => 'Nalgonda', 'state_id' => 1],
            ['name' => 'Nellore', 'state_id' => 1],
            ['name' => 'Nizamabad', 'state_id' => 1],
            ['name' => 'Prakasam', 'state_id' => 1],
            ['name' => 'Rangareddi', 'state_id' => 1],
            ['name' => 'Srikakulam', 'state_id' => 1],
            ['name' => 'Vishakhapatnam', 'state_id' => 1],
            ['name' => 'Vizianagaram', 'state_id' => 1],
            ['name' => 'Warangal', 'state_id' => 1],
            ['name' => 'West Godavari', 'state_id' => 1],
            ['name' => 'Anjaw', 'state_id' => 3],
            ['name' => 'Changlang', 'state_id' => 3],
            ['name' => 'East Kameng', 'state_id' => 3],
            ['name' => 'Lohit', 'state_id' => 3],
            ['name' => 'Lower Subansiri', 'state_id' => 3],
            ['name' => 'Papum Pare', 'state_id' => 3],
            ['name' => 'Tirap', 'state_id' => 3],
            ['name' => 'Dibang Valley', 'state_id' => 3],
            ['name' => 'Upper Subansiri', 'state_id' => 3],
            ['name' => 'West Kameng', 'state_id' => 3],
            ['name' => 'Barpeta', 'state_id' => 2],
            ['name' => 'Bongaigaon', 'state_id' => 2],
            ['name' => 'Cachar', 'state_id' => 2],
            ['name' => 'Darrang', 'state_id' => 2],
            ['name' => 'Dhemaji', 'state_id' => 2],
            ['name' => 'Dhubri', 'state_id' => 2],
            ['name' => 'Dibrugarh', 'state_id' => 2],
            ['name' => 'Goalpara', 'state_id' => 2],
            ['name' => 'Golaghat', 'state_id' => 2],
            ['name' => 'Hailakandi', 'state_id' => 2],
            ['name' => 'Jorhat', 'state_id' => 2],
            ['name' => 'Karbi Anglong', 'state_id' => 2],
            ['name' => 'Karimganj', 'state_id' => 2],
            ['name' => 'Kokrajhar', 'state_id' => 2],
            ['name' => 'Lakhimpur', 'state_id' => 2],
            ['name' => 'Marigaon', 'state_id' => 2],
            ['name' => 'Nagaon', 'state_id' => 2],
            ['name' => 'Nalbari', 'state_id' => 2],
            ['name' => 'North Cachar Hills', 'state_id' => 2],
            ['name' => 'Sibsagar', 'state_id' => 2],
            ['name' => 'Sonitpur', 'state_id' => 2],
            ['name' => 'Tinsukia', 'state_id' => 2],
            ['name' => 'Araria', 'state_id' => 4],
            ['name' => 'Aurangabad', 'state_id' => 4],
            ['name' => 'Banka', 'state_id' => 4],
            ['name' => 'Begusarai', 'state_id' => 4],
            ['name' => 'Bhagalpur', 'state_id' => 4],
            ['name' => 'Bhojpur', 'state_id' => 4],
            ['name' => 'Buxar', 'state_id' => 4],
            ['name' => 'Darbhanga', 'state_id' => 4],
            ['name' => 'Purba Champaran', 'state_id' => 4],
            ['name' => 'Gaya', 'state_id' => 4],
            ['name' => 'Gopalganj', 'state_id' => 4],
            ['name' => 'Jamui', 'state_id' => 4],
            ['name' => 'Jehanabad', 'state_id' => 4],
            ['name' => 'Khagaria', 'state_id' => 4],
            ['name' => 'Kishanganj', 'state_id' => 4],
            ['name' => 'Kaimur', 'state_id' => 4],
            ['name' => 'Katihar', 'state_id' => 4],
            ['name' => 'Lakhisarai', 'state_id' => 4],
            ['name' => 'Madhubani', 'state_id' => 4],
            ['name' => 'Munger', 'state_id' => 4],
            ['name' => 'Madhepura', 'state_id' => 4],
            ['name' => 'Muzaffarpur', 'state_id' => 4],
            ['name' => 'Nalanda', 'state_id' => 4],
            ['name' => 'Nawada', 'state_id' => 4],
            ['name' => 'Patna', 'state_id' => 4],
            ['name' => 'Purnia', 'state_id' => 4],
            ['name' => 'Rohtas', 'state_id' => 4],
            ['name' => 'Saharsa', 'state_id' => 4],
            ['name' => 'Samastipur', 'state_id' => 4],
            ['name' => 'Sheohar', 'state_id' => 4],
            ['name' => 'Sheikhpura', 'state_id' => 4],
            ['name' => 'Saran', 'state_id' => 4],
            ['name' => 'Sitamarhi', 'state_id' => 4],
            ['name' => 'Supaul', 'state_id' => 4],
            ['name' => 'Siwan', 'state_id' => 4],
            ['name' => 'Vaishali', 'state_id' => 4],
            ['name' => 'Pashchim Champaran', 'state_id' => 4],
            ['name' => 'Bastar', 'state_id' => 36],
            ['name' => 'Bilaspur', 'state_id' => 36],
            ['name' => 'Dantewada', 'state_id' => 36],
            ['name' => 'Dhamtari', 'state_id' => 36],
            ['name' => 'Durg', 'state_id' => 36],
            ['name' => 'Jashpur', 'state_id' => 36],
            ['name' => 'Janjgir-Champa', 'state_id' => 36],
            ['name' => 'Korba', 'state_id' => 36],
            ['name' => 'Koriya', 'state_id' => 36],
            ['name' => 'Kanker', 'state_id' => 36],
            ['name' => 'Kawardha', 'state_id' => 36],
            ['name' => 'Mahasamund', 'state_id' => 36],
            ['name' => 'Raigarh', 'state_id' => 36],
            ['name' => 'Rajnandgaon', 'state_id' => 36],
            ['name' => 'Raipur', 'state_id' => 36],
            ['name' => 'Surguja', 'state_id' => 36],
            ['name' => 'Diu', 'state_id' => 29],
            ['name' => 'Daman', 'state_id' => 29],
            ['name' => 'Central Delhi', 'state_id' => 25],
            ['name' => 'East Delhi', 'state_id' => 25],
            ['name' => 'New Delhi', 'state_id' => 25],
            ['name' => 'North Delhi', 'state_id' => 25],
            ['name' => 'North East Delhi', 'state_id' => 25],
            ['name' => 'North West Delhi', 'state_id' => 25],
            ['name' => 'South Delhi', 'state_id' => 25],
            ['name' => 'South West Delhi', 'state_id' => 25],
            ['name' => 'West Delhi', 'state_id' => 25],
            ['name' => 'North Goa', 'state_id' => 26],
            ['name' => 'South Goa', 'state_id' => 26],
            ['name' => 'Ahmedabad', 'state_id' => 5],
            ['name' => 'Amreli District', 'state_id' => 5],
            ['name' => 'Anand', 'state_id' => 5],
            ['name' => 'Banaskantha', 'state_id' => 5],
            ['name' => 'Bharuch', 'state_id' => 5],
            ['name' => 'Bhavnagar', 'state_id' => 5],
            ['name' => 'Dahod', 'state_id' => 5],
            ['name' => 'The Dangs', 'state_id' => 5],
            ['name' => 'Gandhinagar', 'state_id' => 5],
            ['name' => 'Jamnagar', 'state_id' => 5],
            ['name' => 'Junagadh', 'state_id' => 5],
            ['name' => 'Kutch', 'state_id' => 5],
            ['name' => 'Kheda', 'state_id' => 5],
            ['name' => 'Mehsana', 'state_id' => 5],
            ['name' => 'Narmada', 'state_id' => 5],
            ['name' => 'Navsari', 'state_id' => 5],
            ['name' => 'Patan', 'state_id' => 5],
            ['name' => 'Panchmahal', 'state_id' => 5],
            ['name' => 'Porbandar', 'state_id' => 5],
            ['name' => 'Rajkot', 'state_id' => 5],
            ['name' => 'Sabarkantha', 'state_id' => 5],
            ['name' => 'Surendranagar', 'state_id' => 5],
            ['name' => 'Surat', 'state_id' => 5],
            ['name' => 'Vadodara', 'state_id' => 5],
            ['name' => 'Valsad', 'state_id' => 5],
            ['name' => 'Ambala', 'state_id' => 6],
            ['name' => 'Bhiwani', 'state_id' => 6],
            ['name' => 'Faridabad', 'state_id' => 6],
            ['name' => 'Fatehabad', 'state_id' => 6],
            ['name' => 'Gurgaon', 'state_id' => 6],
            ['name' => 'Hissar', 'state_id' => 6],
            ['name' => 'Jhajjar', 'state_id' => 6],
            ['name' => 'Jind', 'state_id' => 6],
            ['name' => 'Karnal', 'state_id' => 6],
            ['name' => 'Kaithal', 'state_id' => 6],
            ['name' => 'Kurukshetra', 'state_id' => 6],
            ['name' => 'Mahendragarh', 'state_id' => 6],
            ['name' => 'Mewat', 'state_id' => 6],
            ['name' => 'Panchkula', 'state_id' => 6],
            ['name' => 'Panipat', 'state_id' => 6],
            ['name' => 'Rewari', 'state_id' => 6],
            ['name' => 'Rohtak', 'state_id' => 6],
            ['name' => 'Sirsa', 'state_id' => 6],
            ['name' => 'Sonepat', 'state_id' => 6],
            ['name' => 'Yamuna Nagar', 'state_id' => 6],
            ['name' => 'Palwal', 'state_id' => 6],
            ['name' => 'Bilaspur', 'state_id' => 7],
            ['name' => 'Chamba', 'state_id' => 7],
            ['name' => 'Hamirpur', 'state_id' => 7],
            ['name' => 'Kangra', 'state_id' => 7],
            ['name' => 'Kinnaur', 'state_id' => 7],
            ['name' => 'Kulu', 'state_id' => 7],
            ['name' => 'Lahaul and Spiti', 'state_id' => 7],
            ['name' => 'Mandi', 'state_id' => 7],
            ['name' => 'Shimla', 'state_id' => 7],
            ['name' => 'Sirmaur', 'state_id' => 7],
            ['name' => 'Solan', 'state_id' => 7],
            ['name' => 'Una', 'state_id' => 7],
            ['name' => 'Anantnag', 'state_id' => 8],
            ['name' => 'Badgam', 'state_id' => 8],
            ['name' => 'Bandipore', 'state_id' => 8],
            ['name' => 'Baramula', 'state_id' => 8],
            ['name' => 'Doda', 'state_id' => 8],
            ['name' => 'Jammu', 'state_id' => 8],
            ['name' => 'Kargil', 'state_id' => 8],
            ['name' => 'Kathua', 'state_id' => 8],
            ['name' => 'Kupwara', 'state_id' => 8],
            ['name' => 'Leh', 'state_id' => 8],
            ['name' => 'Poonch', 'state_id' => 8],
            ['name' => 'Pulwama', 'state_id' => 8],
            ['name' => 'Rajauri', 'state_id' => 8],
            ['name' => 'Srinagar', 'state_id' => 8],
            ['name' => 'Samba', 'state_id' => 8],
            ['name' => 'Udhampur', 'state_id' => 8],
            ['name' => 'Bokaro', 'state_id' => 34],
            ['name' => 'Chatra', 'state_id' => 34],
            ['name' => 'Deoghar', 'state_id' => 34],
            ['name' => 'Dhanbad', 'state_id' => 34],
            ['name' => 'Dumka', 'state_id' => 34],
            ['name' => 'Purba Singhbhum', 'state_id' => 34],
            ['name' => 'Garhwa', 'state_id' => 34],
            ['name' => 'Giridih', 'state_id' => 34],
            ['name' => 'Godda', 'state_id' => 34],
            ['name' => 'Gumla', 'state_id' => 34],
            ['name' => 'Hazaribagh', 'state_id' => 34],
            ['name' => 'Koderma', 'state_id' => 34],
            ['name' => 'Lohardaga', 'state_id' => 34],
            ['name' => 'Pakur', 'state_id' => 34],
            ['name' => 'Palamu', 'state_id' => 34],
            ['name' => 'Ranchi', 'state_id' => 34],
            ['name' => 'Sahibganj', 'state_id' => 34],
            ['name' => 'Seraikela and Kharsawan', 'state_id' => 34],
            ['name' => 'Pashchim Singhbhum', 'state_id' => 34],
            ['name' => 'Ramgarh', 'state_id' => 34],
            ['name' => 'Bidar', 'state_id' => 9],
            ['name' => 'Belgaum', 'state_id' => 9],
            ['name' => 'Bijapur', 'state_id' => 9],
            ['name' => 'Bagalkot', 'state_id' => 9],
            ['name' => 'Bellary', 'state_id' => 9],
            ['name' => 'Bangalore Rural District', 'state_id' => 9],
            ['name' => 'Bangalore Urban District', 'state_id' => 9],
            ['name' => 'Chamarajnagar', 'state_id' => 9],
            ['name' => 'Chikmagalur', 'state_id' => 9],
            ['name' => 'Chitradurga', 'state_id' => 9],
            ['name' => 'Davanagere', 'state_id' => 9],
            ['name' => 'Dharwad', 'state_id' => 9],
            ['name' => 'Dakshina Kannada', 'state_id' => 9],
            ['name' => 'Gadag', 'state_id' => 9],
            ['name' => 'Gulbarga', 'state_id' => 9],
            ['name' => 'Hassan', 'state_id' => 9],
            ['name' => 'Haveri District', 'state_id' => 9],
            ['name' => 'Kodagu', 'state_id' => 9],
            ['name' => 'Kolar', 'state_id' => 9],
            ['name' => 'Koppal', 'state_id' => 9],
            ['name' => 'Mandya', 'state_id' => 9],
            ['name' => 'Mysore', 'state_id' => 9],
            ['name' => 'Raichur', 'state_id' => 9],
            ['name' => 'Shimoga', 'state_id' => 9],
            ['name' => 'Tumkur', 'state_id' => 9],
            ['name' => 'Udupi', 'state_id' => 9],
            ['name' => 'Uttara Kannada', 'state_id' => 9],
            ['name' => 'Ramanagara', 'state_id' => 9],
            ['name' => 'Chikballapur', 'state_id' => 9],
            ['name' => 'Yadagiri', 'state_id' => 9],
            ['name' => 'Alappuzha', 'state_id' => 10],
            ['name' => 'Ernakulam', 'state_id' => 10],
            ['name' => 'Idukki', 'state_id' => 10],
            ['name' => 'Kollam', 'state_id' => 10],
            ['name' => 'Kannur', 'state_id' => 10],
            ['name' => 'Kasaragod', 'state_id' => 10],
            ['name' => 'Kottayam', 'state_id' => 10],
            ['name' => 'Kozhikode', 'state_id' => 10],
            ['name' => 'Malappuram', 'state_id' => 10],
            ['name' => 'Palakkad', 'state_id' => 10],
            ['name' => 'Pathanamthitta', 'state_id' => 10],
            ['name' => 'Thrissur', 'state_id' => 10],
            ['name' => 'Thiruvananthapuram', 'state_id' => 10],
            ['name' => 'Wayanad', 'state_id' => 10],
            ['name' => 'Alirajpur', 'state_id' => 11],
            ['name' => 'Anuppur', 'state_id' => 11],
            ['name' => 'Ashok Nagar', 'state_id' => 11],
            ['name' => 'Balaghat', 'state_id' => 11],
            ['name' => 'Barwani', 'state_id' => 11],
            ['name' => 'Betul', 'state_id' => 11],
            ['name' => 'Bhind', 'state_id' => 11],
            ['name' => 'Bhopal', 'state_id' => 11],
            ['name' => 'Burhanpur', 'state_id' => 11],
            ['name' => 'Chhatarpur', 'state_id' => 11],
            ['name' => 'Chhindwara', 'state_id' => 11],
            ['name' => 'Damoh', 'state_id' => 11],
            ['name' => 'Datia', 'state_id' => 11],
            ['name' => 'Dewas', 'state_id' => 11],
            ['name' => 'Dhar', 'state_id' => 11],
            ['name' => 'Dindori', 'state_id' => 11],
            ['name' => 'Guna', 'state_id' => 11],
            ['name' => 'Gwalior', 'state_id' => 11],
            ['name' => 'Harda', 'state_id' => 11],
            ['name' => 'Hoshangabad', 'state_id' => 11],
            ['name' => 'Indore', 'state_id' => 11],
            ['name' => 'Jabalpur', 'state_id' => 11],
            ['name' => 'Jhabua', 'state_id' => 11],
            ['name' => 'Katni', 'state_id' => 11],
            ['name' => 'Khandwa', 'state_id' => 11],
            ['name' => 'Khargone', 'state_id' => 11],
            ['name' => 'Mandla', 'state_id' => 11],
            ['name' => 'Mandsaur', 'state_id' => 11],
            ['name' => 'Morena', 'state_id' => 11],
            ['name' => 'Narsinghpur', 'state_id' => 11],
            ['name' => 'Neemuch', 'state_id' => 11],
            ['name' => 'Panna', 'state_id' => 11],
            ['name' => 'Rewa', 'state_id' => 11],
            ['name' => 'Rajgarh', 'state_id' => 11],
            ['name' => 'Ratlam', 'state_id' => 11],
            ['name' => 'Raisen', 'state_id' => 11],
            ['name' => 'Sagar', 'state_id' => 11],
            ['name' => 'Satna', 'state_id' => 11],
            ['name' => 'Sehore', 'state_id' => 11],
            ['name' => 'Seoni', 'state_id' => 11],
            ['name' => 'Shahdol', 'state_id' => 11],
            ['name' => 'Shajapur', 'state_id' => 11],
            ['name' => 'Sheopur', 'state_id' => 11],
            ['name' => 'Shivpuri', 'state_id' => 11],
            ['name' => 'Sidhi', 'state_id' => 11],
            ['name' => 'Singrauli', 'state_id' => 11],
            ['name' => 'Tikamgarh', 'state_id' => 11],
            ['name' => 'Ujjain', 'state_id' => 11],
            ['name' => 'Umaria', 'state_id' => 11],
            ['name' => 'Vidisha', 'state_id' => 11],
            ['name' => 'Ahmednagar', 'state_id' => 12],
            ['name' => 'Akola', 'state_id' => 12],
            ['name' => 'Amrawati', 'state_id' => 12],
            ['name' => 'Aurangabad', 'state_id' => 12],
            ['name' => 'Bhandara', 'state_id' => 12],
            ['name' => 'Beed', 'state_id' => 12],
            ['name' => 'Buldhana', 'state_id' => 12],
            ['name' => 'Chandrapur', 'state_id' => 12],
            ['name' => 'Dhule', 'state_id' => 12],
            ['name' => 'Gadchiroli', 'state_id' => 12],
            ['name' => 'Gondiya', 'state_id' => 12],
            ['name' => 'Hingoli', 'state_id' => 12],
            ['name' => 'Jalgaon', 'state_id' => 12],
            ['name' => 'Jalna', 'state_id' => 12],
            ['name' => 'Kolhapur', 'state_id' => 12],
            ['name' => 'Latur', 'state_id' => 12],
            ['name' => 'Mumbai City', 'state_id' => 12],
            ['name' => 'Mumbai suburban', 'state_id' => 12],
            ['name' => 'Nandurbar', 'state_id' => 12],
            ['name' => 'Nanded', 'state_id' => 12],
            ['name' => 'Nagpur', 'state_id' => 12],
            ['name' => 'Nashik', 'state_id' => 12],
            ['name' => 'Osmanabad', 'state_id' => 12],
            ['name' => 'Parbhani', 'state_id' => 12],
            ['name' => 'Pune', 'state_id' => 12],
            ['name' => 'Raigad', 'state_id' => 12],
            ['name' => 'Ratnagiri', 'state_id' => 12],
            ['name' => 'Sindhudurg', 'state_id' => 12],
            ['name' => 'Sangli', 'state_id' => 12],
            ['name' => 'Solapur', 'state_id' => 12],
            ['name' => 'Satara', 'state_id' => 12],
            ['name' => 'Thane', 'state_id' => 12],
            ['name' => 'Wardha', 'state_id' => 12],
            ['name' => 'Washim', 'state_id' => 12],
            ['name' => 'Yavatmal', 'state_id' => 12],
            ['name' => 'Bishnupur', 'state_id' => 13],
            ['name' => 'Churachandpur', 'state_id' => 13],
            ['name' => 'Chandel', 'state_id' => 13],
            ['name' => 'Imphal East', 'state_id' => 13],
            ['name' => 'Senapati', 'state_id' => 13],
            ['name' => 'Tamenglong', 'state_id' => 13],
            ['name' => 'Thoubal', 'state_id' => 13],
            ['name' => 'Ukhrul', 'state_id' => 13],
            ['name' => 'Imphal West', 'state_id' => 13],
            ['name' => 'East Garo Hills', 'state_id' => 14],
            ['name' => 'East Khasi Hills', 'state_id' => 14],
            ['name' => 'Jaintia Hills', 'state_id' => 14],
            ['name' => 'Ri-Bhoi', 'state_id' => 14],
            ['name' => 'South Garo Hills', 'state_id' => 14],
            ['name' => 'West Garo Hills', 'state_id' => 14],
            ['name' => 'West Khasi Hills', 'state_id' => 14],
            ['name' => 'Aizawl', 'state_id' => 15],
            ['name' => 'Champhai', 'state_id' => 15],
            ['name' => 'Kolasib', 'state_id' => 15],
            ['name' => 'Lawngtlai', 'state_id' => 15],
            ['name' => 'Lunglei', 'state_id' => 15],
            ['name' => 'Mamit', 'state_id' => 15],
            ['name' => 'Saiha', 'state_id' => 15],
            ['name' => 'Serchhip', 'state_id' => 15],
            ['name' => 'Dimapur', 'state_id' => 16],
            ['name' => 'Kohima', 'state_id' => 16],
            ['name' => 'Mokokchung', 'state_id' => 16],
            ['name' => 'Mon', 'state_id' => 16],
            ['name' => 'Phek', 'state_id' => 16],
            ['name' => 'Tuensang', 'state_id' => 16],
            ['name' => 'Wokha', 'state_id' => 16],
            ['name' => 'Zunheboto', 'state_id' => 16],
            ['name' => 'Angul', 'state_id' => 17],
            ['name' => 'Boudh', 'state_id' => 17],
            ['name' => 'Bhadrak', 'state_id' => 17],
            ['name' => 'Bolangir', 'state_id' => 17],
            ['name' => 'Bargarh', 'state_id' => 17],
            ['name' => 'Baleswar', 'state_id' => 17],
            ['name' => 'Cuttack', 'state_id' => 17],
            ['name' => 'Debagarh', 'state_id' => 17],
            ['name' => 'Dhenkanal', 'state_id' => 17],
            ['name' => 'Ganjam', 'state_id' => 17],
            ['name' => 'Gajapati', 'state_id' => 17],
            ['name' => 'Jharsuguda', 'state_id' => 17],
            ['name' => 'Jajapur', 'state_id' => 17],
            ['name' => 'Jagatsinghpur', 'state_id' => 17],
            ['name' => 'Khordha', 'state_id' => 17],
            ['name' => 'Kendujhar', 'state_id' => 17],
            ['name' => 'Kalahandi', 'state_id' => 17],
            ['name' => 'Kandhamal', 'state_id' => 17],
            ['name' => 'Koraput', 'state_id' => 17],
            ['name' => 'Kendrapara', 'state_id' => 17],
            ['name' => 'Malkangiri', 'state_id' => 17],
            ['name' => 'Mayurbhanj', 'state_id' => 17],
            ['name' => 'Nabarangpur', 'state_id' => 17],
            ['name' => 'Nuapada', 'state_id' => 17],
            ['name' => 'Nayagarh', 'state_id' => 17],
            ['name' => 'Puri', 'state_id' => 17],
            ['name' => 'Rayagada', 'state_id' => 17],
            ['name' => 'Sambalpur', 'state_id' => 17],
            ['name' => 'Subarnapur', 'state_id' => 17],
            ['name' => 'Sundargarh', 'state_id' => 17],
            ['name' => 'Karaikal', 'state_id' => 27],
            ['name' => 'Mahe', 'state_id' => 27],
            ['name' => 'Puducherry', 'state_id' => 27],
            ['name' => 'Yanam', 'state_id' => 27],
            ['name' => 'Amritsar', 'state_id' => 18],
            ['name' => 'Bathinda', 'state_id' => 18],
            ['name' => 'Firozpur', 'state_id' => 18],
            ['name' => 'Faridkot', 'state_id' => 18],
            ['name' => 'Fatehgarh Sahib', 'state_id' => 18],
            ['name' => 'Gurdaspur', 'state_id' => 18],
            ['name' => 'Hoshiarpur', 'state_id' => 18],
            ['name' => 'Jalandhar', 'state_id' => 18],
            ['name' => 'Kapurthala', 'state_id' => 18],
            ['name' => 'Ludhiana', 'state_id' => 18],
            ['name' => 'Mansa', 'state_id' => 18],
            ['name' => 'Moga', 'state_id' => 18],
            ['name' => 'Mukatsar', 'state_id' => 18],
            ['name' => 'Nawan Shehar', 'state_id' => 18],
            ['name' => 'Patiala', 'state_id' => 18],
            ['name' => 'Rupnagar', 'state_id' => 18],
            ['name' => 'Sangrur', 'state_id' => 18],
            ['name' => 'Ajmer', 'state_id' => 19],
            ['name' => 'Alwar', 'state_id' => 19],
            ['name' => 'Bikaner', 'state_id' => 19],
            ['name' => 'Barmer', 'state_id' => 19],
            ['name' => 'Banswara', 'state_id' => 19],
            ['name' => 'Bharatpur', 'state_id' => 19],
            ['name' => 'Baran', 'state_id' => 19],
            ['name' => 'Bundi', 'state_id' => 19],
            ['name' => 'Bhilwara', 'state_id' => 19],
            ['name' => 'Churu', 'state_id' => 19],
            ['name' => 'Chittorgarh', 'state_id' => 19],
            ['name' => 'Dausa', 'state_id' => 19],
            ['name' => 'Dholpur', 'state_id' => 19],
            ['name' => 'Dungapur', 'state_id' => 19],
            ['name' => 'Ganganagar', 'state_id' => 19],
            ['name' => 'Hanumangarh', 'state_id' => 19],
            ['name' => 'Juhnjhunun', 'state_id' => 19],
            ['name' => 'Jalore', 'state_id' => 19],
            ['name' => 'Jodhpur', 'state_id' => 19],
            ['name' => 'Jaipur', 'state_id' => 19],
            ['name' => 'Jaisalmer', 'state_id' => 19],
            ['name' => 'Jhalawar', 'state_id' => 19],
            ['name' => 'Karauli', 'state_id' => 19],
            ['name' => 'Kota', 'state_id' => 19],
            ['name' => 'Nagaur', 'state_id' => 19],
            ['name' => 'Pali', 'state_id' => 19],
            ['name' => 'Pratapgarh', 'state_id' => 19],
            ['name' => 'Rajsamand', 'state_id' => 19],
            ['name' => 'Sikar', 'state_id' => 19],
            ['name' => 'Sawai Madhopur', 'state_id' => 19],
            ['name' => 'Sirohi', 'state_id' => 19],
            ['name' => 'Tonk', 'state_id' => 19],
            ['name' => 'Udaipur', 'state_id' => 19],
            ['name' => 'East Sikkim', 'state_id' => 20],
            ['name' => 'North Sikkim', 'state_id' => 20],
            ['name' => 'South Sikkim', 'state_id' => 20],
            ['name' => 'West Sikkim', 'state_id' => 20],
            ['name' => 'Ariyalur', 'state_id' => 21],
            ['name' => 'Chennai', 'state_id' => 21],
            ['name' => 'Coimbatore', 'state_id' => 21],
            ['name' => 'Cuddalore', 'state_id' => 21],
            ['name' => 'Dharmapuri', 'state_id' => 21],
            ['name' => 'Dindigul', 'state_id' => 21],
            ['name' => 'Erode', 'state_id' => 21],
            ['name' => 'Kanchipuram', 'state_id' => 21],
            ['name' => 'Kanyakumari', 'state_id' => 21],
            ['name' => 'Karur', 'state_id' => 21],
            ['name' => 'Madurai', 'state_id' => 21],
            ['name' => 'Nagapattinam', 'state_id' => 21],
            ['name' => 'The Nilgiris', 'state_id' => 21],
            ['name' => 'Namakkal', 'state_id' => 21],
            ['name' => 'Perambalur', 'state_id' => 21],
            ['name' => 'Pudukkottai', 'state_id' => 21],
            ['name' => 'Ramanathapuram', 'state_id' => 21],
            ['name' => 'Salem', 'state_id' => 21],
            ['name' => 'Sivagangai', 'state_id' => 21],
            ['name' => 'Tiruppur', 'state_id' => 21],
            ['name' => 'Tiruchirappalli', 'state_id' => 21],
            ['name' => 'Theni', 'state_id' => 21],
            ['name' => 'Tirunelveli', 'state_id' => 21],
            ['name' => 'Thanjavur', 'state_id' => 21],
            ['name' => 'Thoothukudi', 'state_id' => 21],
            ['name' => 'Thiruvallur', 'state_id' => 21],
            ['name' => 'Thiruvarur', 'state_id' => 21],
            ['name' => 'Tiruvannamalai', 'state_id' => 21],
            ['name' => 'Vellore', 'state_id' => 21],
            ['name' => 'Villupuram', 'state_id' => 21],
            ['name' => 'Dhalai', 'state_id' => 22],
            ['name' => 'North Tripura', 'state_id' => 22],
            ['name' => 'South Tripura', 'state_id' => 22],
            ['name' => 'West Tripura', 'state_id' => 22],
            ['name' => 'Almora', 'state_id' => 33],
            ['name' => 'Bageshwar', 'state_id' => 33],
            ['name' => 'Chamoli', 'state_id' => 33],
            ['name' => 'Champawat', 'state_id' => 33],
            ['name' => 'Dehradun', 'state_id' => 33],
            ['name' => 'Haridwar', 'state_id' => 33],
            ['name' => 'Nainital', 'state_id' => 33],
            ['name' => 'Pauri Garhwal', 'state_id' => 33],
            ['name' => 'Pithoragharh', 'state_id' => 33],
            ['name' => 'Rudraprayag', 'state_id' => 33],
            ['name' => 'Tehri Garhwal', 'state_id' => 33],
            ['name' => 'Udham Singh Nagar', 'state_id' => 33],
            ['name' => 'Uttarkashi', 'state_id' => 33],
            ['name' => 'Agra', 'state_id' => 23],
            ['name' => 'Allahabad', 'state_id' => 23],
            ['name' => 'Aligarh', 'state_id' => 23],
            ['name' => 'Ambedkar Nagar', 'state_id' => 23],
            ['name' => 'Auraiya', 'state_id' => 23],
            ['name' => 'Azamgarh', 'state_id' => 23],
            ['name' => 'Barabanki', 'state_id' => 23],
            ['name' => 'Badaun', 'state_id' => 23],
            ['name' => 'Bagpat', 'state_id' => 23],
            ['name' => 'Bahraich', 'state_id' => 23],
            ['name' => 'Bijnor', 'state_id' => 23],
            ['name' => 'Ballia', 'state_id' => 23],
            ['name' => 'Banda', 'state_id' => 23],
            ['name' => 'Balrampur', 'state_id' => 23],
            ['name' => 'Bareilly', 'state_id' => 23],
            ['name' => 'Basti', 'state_id' => 23],
            ['name' => 'Bulandshahr', 'state_id' => 23],
            ['name' => 'Chandauli', 'state_id' => 23],
            ['name' => 'Chitrakoot', 'state_id' => 23],
            ['name' => 'Deoria', 'state_id' => 23],
            ['name' => 'Etah', 'state_id' => 23],
            ['name' => 'Kanshiram Nagar', 'state_id' => 23],
            ['name' => 'Etawah', 'state_id' => 23],
            ['name' => 'Firozabad', 'state_id' => 23],
            ['name' => 'Farrukhabad', 'state_id' => 23],
            ['name' => 'Fatehpur', 'state_id' => 23],
            ['name' => 'Faizabad', 'state_id' => 23],
            ['name' => 'Gautam Buddha Nagar', 'state_id' => 23],
            ['name' => 'Gonda', 'state_id' => 23],
            ['name' => 'Ghazipur', 'state_id' => 23],
            ['name' => 'Gorkakhpur', 'state_id' => 23],
            ['name' => 'Ghaziabad', 'state_id' => 23],
            ['name' => 'Hamirpur', 'state_id' => 23],
            ['name' => 'Hardoi', 'state_id' => 23],
            ['name' => 'Mahamaya Nagar', 'state_id' => 23],
            ['name' => 'Jhansi', 'state_id' => 23],
            ['name' => 'Jalaun', 'state_id' => 23],
            ['name' => 'Jyotiba Phule Nagar', 'state_id' => 23],
            ['name' => 'Jaunpur District', 'state_id' => 23],
            ['name' => 'Kanpur Dehat', 'state_id' => 23],
            ['name' => 'Kannauj', 'state_id' => 23],
            ['name' => 'Kanpur Nagar', 'state_id' => 23],
            ['name' => 'Kaushambi', 'state_id' => 23],
            ['name' => 'Kushinagar', 'state_id' => 23],
            ['name' => 'Lalitpur', 'state_id' => 23],
            ['name' => 'Lakhimpur Kheri', 'state_id' => 23],
            ['name' => 'Lucknow', 'state_id' => 23],
            ['name' => 'Mau', 'state_id' => 23],
            ['name' => 'Meerut', 'state_id' => 23],
            ['name' => 'Maharajganj', 'state_id' => 23],
            ['name' => 'Mahoba', 'state_id' => 23],
            ['name' => 'Mirzapur', 'state_id' => 23],
            ['name' => 'Moradabad', 'state_id' => 23],
            ['name' => 'Mainpuri', 'state_id' => 23],
            ['name' => 'Mathura', 'state_id' => 23],
            ['name' => 'Muzaffarnagar', 'state_id' => 23],
            ['name' => 'Pilibhit', 'state_id' => 23],
            ['name' => 'Pratapgarh', 'state_id' => 23],
            ['name' => 'Rampur', 'state_id' => 23],
            ['name' => 'Rae Bareli', 'state_id' => 23],
            ['name' => 'Saharanpur', 'state_id' => 23],
            ['name' => 'Sitapur', 'state_id' => 23],
            ['name' => 'Shahjahanpur', 'state_id' => 23],
            ['name' => 'Sant Kabir Nagar', 'state_id' => 23],
            ['name' => 'Siddharthnagar', 'state_id' => 23],
            ['name' => 'Sonbhadra', 'state_id' => 23],
            ['name' => 'Sant Ravidas Nagar', 'state_id' => 23],
            ['name' => 'Sultanpur', 'state_id' => 23],
            ['name' => 'Shravasti', 'state_id' => 23],
            ['name' => 'Unnao', 'state_id' => 23],
            ['name' => 'Varanasi', 'state_id' => 23],
            ['name' => 'Birbhum', 'state_id' => 24],
            ['name' => 'Bankura', 'state_id' => 24],
            ['name' => 'Bardhaman', 'state_id' => 24],
            ['name' => 'Darjeeling', 'state_id' => 24],
            ['name' => 'Dakshin Dinajpur', 'state_id' => 24],
            ['name' => 'Hooghly', 'state_id' => 24],
            ['name' => 'Howrah', 'state_id' => 24],
            ['name' => 'Jalpaiguri', 'state_id' => 24],
            ['name' => 'Cooch Behar', 'state_id' => 24],
            ['name' => 'Kolkata', 'state_id' => 24],
            ['name' => 'Malda', 'state_id' => 24],
            ['name' => 'Midnapore', 'state_id' => 24],
            ['name' => 'Murshidabad', 'state_id' => 24],
            ['name' => 'Nadia', 'state_id' => 24],
            ['name' => 'North 24 Parganas', 'state_id' => 24],
            ['name' => 'South 24 Parganas', 'state_id' => 24],
            ['name' => 'Purulia', 'state_id' => 24],
            ['name' => 'Uttar Dinajpur', 'state_id' => 24],
        ]);
    }
}
